export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const SIGNUP_USER = "SIGNUP_USER"
export const AUTH_ERRROR = "AUTH_ERRROR"
export const EMAIL_VERIFICATION = "EMAIL_VERIFICATION"

export const SET_ALERT = "SET_ALERT"
export const RESET_ALERT = "RESET_ALERT"