export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const MEDICINES_LOADING = "MEDICINES_LOADING"
export const MEDICINES_FAILED = "MEDICINES_FAILED"
export const MEDICINES_RETRIEVED = "MEDICINES_RETRIEVED"
export const MEDICINES_ADD = "MEDICINES_ADD"
export const MEDICINES_UPDATE = "MEDICINES_UPDATE"
export const MEDICINES_DELETE = "MEDICINES_DELETE"

export const TOGGLE_THEME = "TOGGLE_THEME"